steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/rodxshop/shoppingServer/rodx-shop-be', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/rodxshop/shoppingServer/rodx-shop-be']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'rodx-shop-be', '--image', 'asia.gcr.io/rodxshop/shoppingServer/rodx-shop-be', '--region', 'asia-southeast1', '--quiet']
images:
- asia.gcr.io/rodxshop/shoppingServer/rodx-shop-be